name: Trading Bot Runner

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    # Runs at 01:30 UTC every day, which corresponds to 08:30 in Thailand (UTC+7)
    - cron: '30 1 * * *'

jobs:
  run-trading-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # cache pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run trading bot
        env:
          BOT_EMAIL_SENDER: ${{ secrets.BOT_EMAIL_SENDER }}
          BOT_EMAIL_PASSWORD: ${{ secrets.BOT_EMAIL_PASSWORD }}
          BOT_EMAIL_RECIPIENT: ${{ secrets.BOT_EMAIL_RECIPIENT }}
        run: python main.py both
